development:
  adapter: "sqlite3"
  username: "root"
  password: "123456"
  host: "localhost"
  database: "db/development.sqlite3"
  encoding: "unicode"
  pool: 50

production:
  adapter: postgresql
  encoding: unicode
  database: dc36dja8ltic9m
  username: xolcsjobimccmb
  password: 0af65caf3ecf58983c8d245aae5d44c3712281b85a49adb069cb84d7ffeaa22f
  host: ec2-54-197-232-155.compute-1.amazonaws.com
  port: 5432
  pool: 50
