development:
  adapter: "mysql2"
  username: "root"
  password: "123456"
  host: "localhost"
  database: "dm-tools"
  encoding: "utf8"
  collation: "utf8_unicode_ci"
  pool: 50

production:
  adapter: "mysql2"
  username: "root"
  password: "123456"
  host: "localhost"
  database: "dm-tools"
  encoding: "utf8"
  collation: "utf8_unicode_ci"
  pool: 50
