development:
  adapter: "mysql2"
  username: "root"
  password: "123456"
  host: "localhost"
  database: "dm-tools"
  encoding: "utf8"
  collation: "utf8_unicode_ci"
  pool: 50

production:
  adapter: "postgresql"
  encoding: "unicode"
  database: "dm-tools"
  pool: 5
  username: "root"
  password: "123456"
  host: "localhost"